name: Release
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
  schedule:
    - cron: '0 2 1 * 1'
  push:
    tags:
      - '*'
      - '!*-alpha*'

jobs:
  linux:
    name: Linux Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          ref: aiapi
      - name: Determine Version
        run: |
          VERSION=$(git describe --tags)
          TAG_NAME=$(git tag --points-at HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      - name: Build Frontend (default)
        env:
          CI: ""
        run: |
          cd web/default
          bun install
          DISABLE_ESLINT_PLUGIN='true' VITE_REACT_APP_VERSION=$VERSION bun run build
          cd ../..
      - name: Build Frontend (classic)
        env:
          CI: ""
        run: |
          cd web/classic
          bun install
          VITE_REACT_APP_VERSION=$VERSION bun run build
          cd ../..
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '>=1.25.1'
      - name: Build Backend (amd64)
        run: |
          go mod download
          go build -ldflags "-s -w -X 'new-api/common.Version=$VERSION' -extldflags '-static'" -o new-api
      - name: Generate checksums
        run: sha256sum new-api > checksums-linux.txt

      - name: Release
        uses: softprops/action-gh-release@v3 # v2
        with:
          tag_name: $TAG_NAME
          generate_release_notes: true
          files: |
            new-api
            checksums-linux.txt
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}